### PR TITLE
Upgrade to Kirkstone

### PR DESCRIPTION
**Pull request by fboudra**

### CODE REVIEW

**Comment by Pillar1989** [comment]
@fboudra  thanks. can I test it now ? do u have simple guide to get start ?

**Comment by fboudra** [comment]
@Pillar1989 yes, it can be tested now. I'll write a quick guide on using it.

```
mkdir mender-seeed && cd mender-seeed

### Get the source code ###

export LTS_YOCTO=kirkstone
git clone -b ${LTS_YOCTO} git://git.yoctoproject.org/poky layers/poky
git clone -b ${LTS_YOCTO} git://git.yoctoproject.org/meta-intel layers/meta-intel
git clone -b ${LTS_YOCTO} https://github.com/mendersoftware/meta-mender layers/meta-mender
git clone -b ${LTS_YOCTO} https://github.com/openembedded/meta-openembedded layers/meta-openembedded
git clone -b ${LTS_YOCTO} https://github.com/fboudra/meta-odyssey-x86.git layers/meta-odyssey-x86

source layers/poky/oe-init-build-env

bitbake-layers add-layer  ../layers/meta-intel
bitbake-layers add-layer  ../layers/meta-odyssey-x86
bitbake-layers add-layer  ../layers/meta-openembedded/meta-oe
bitbake-layers add-layer  ../layers/meta-openembedded/meta-python
bitbake-layers add-layer  ../layers/meta-openembedded/meta-networking
bitbake-layers add-layer  ../layers/meta-mender/meta-mender-core
bitbake-layers add-layer  ../layers/meta-mender/meta-mender-demo

### Edit conf/local.conf and append the following ###

MACHINE = "odyssey-x86-mender"

# Specify which bootloader is used to load other EFI apps
MENDER_EFI_LOADER = "ovmf"

# Set the device file corresponding to the root filesystem partitions
# By default MENDER_STORAGE_DEVICE is /dev/mmcblk0
# Adjust the device to match your requirement e.g. /dev/sda
#MENDER_STORAGE_DEVICE = "/dev/mmcblk0"

### Build ###

bitbake odyssey-image-base
```

**Comment by Pillar1989** [comment]
image
@fboudra  works

**Comment by fboudra** [comment]
@Pillar1989 thanks! Do you mind to branch main and create a kirkstone branch please?

**Comment by Pillar1989** [comment]
Done

**Pull request merged**
